### ISSUE TITLE
Slack link in docs is a dead link.

### ISSUE THREAD

**Issue by inetbiz** [actionsflow/actionsflow#13]
Review the link to slack channel on file https://github.com/actionsflow/actionsflow/blob/main/docs/index.md

**Comment by theowenyoung** [comment]
Thanks @inetbiz , it's really imporntant for me., and sorry for the dead link, it's expired, slack does not allow people to create a never expired inviting link,  so I just made an inviting form to invite people automatically, you can be the first user to experience it.

[Join Actionsflow on Slack](https://forms.gle/9VvTVne6oU7zBCeVA)

Thanks!
