### ISSUE TITLE
Should formatting run before `getItemKey`?

### ISSUE THREAD

**Issue by grantcodes** [actionsflow/actionsflow#16]
## Description

I'm trying to use the api poll trigger to query a json list of upvoted posts (available from https://www.reddit.com/prefs/feeds/).
But the json is quite complicated, so I used the `itemsPath` and `format` options to simplify things, but I think the `deduplicationKey` uses the unprocessed json, which constantly changes and has the id property as a nested item.

If the json formatting was run before the deduplication the poll trigger could be used for much more complicated json.

**Comment by theowenyoung** [comment]
Hi, @grantcodes , yes, I think you're right, `format` and `filtetOutputs` should be run at the first, not it run at the last. I'll give a fix today, and the `deduplicationKey` should support path param like `data.id`, so, it can support more complex situations.

**Comment by theowenyoung** [comment]
@grantcodes Hi, I just released a new version, `format` will be run at the first,  `deduplicationKey ` is also support path format. Now you can try it. Let me know if you have any further question.

**Comment by grantcodes** [comment]
Thanks @theowenyoung it's working great now!
