### ISSUE TITLE
Need a community 

### ISSUE THREAD

**Issue by SettingDust** [actionsflow/actionsflow#24]
Need a community. Such as Telegram group.
需要一个社区，TG 群也可以 :D

**Comment by theowenyoung** [comment]
Thanks, @SettingDust , I created a telegram group just now, and add a invite link at the docs, you can [Join Actionsflow on Telegram](https://t.me/joinchat/fMXYRGHMnK01MjUx) now. (Only me in the group now :) )

**Comment by theowenyoung** [comment]
By the way, there is a slack group of Actionsflow:

- [Join Actionsflow on Slack](https://forms.gle/9VvTVne6oU7zBCeVA) - Chat with other users and contributors on Slack, if you have already joined, please [signin](https://actionsflow.slack.com) directly
