### ISSUE TITLE
Reset cache does not work

### ISSUE THREAD

**Issue by MarcMogdanz** [actionsflow/actionsflow#3]
## Description

When I'm running the GitHub action to reset the cache and then trigger the Actionsflow GitHub action it does not execute my workflows.

### Steps to reproduce

1. Have your workflows run (so that a cache exists)
2. Manually trigger the `Reset Actionsflow Cache` GitHub action via the webinterface
3. Manually trigger the `Actionsflow` GitHub action via the webinterface

You can use my current workflows repository [here](https://github.com/MarcMogdanz/actionsflow-workflows). An example cache reset is [here](https://github.com/MarcMogdanz/actionsflow-workflows/runs/1201682500?check_suite_focus=true) and the corresponding Actionsflow run afterwards is [here](https://github.com/MarcMogdanz/actionsflow-workflows/runs/1201683673?check_suite_focus=true).

### Expected result

After resetting the cache it should run all my workflows, in this case it's about cached RSS feeds.

### Actual result

It does not run the workflows meaning he already "knows" the RSS feeds because the cache probably still exists.

**Comment by theowenyoung** [comment]
@MarcMogdanz Thanks, I reproduce this bug, I'll fix it later.

It seems that it can clean cache first time, but it will be failed at the second time.

Because the reset cache contents are not changed, I'll give it a different empty cache content, then it'll upload success.

Thanks for your report.

**Comment by theowenyoung** [comment]
Hey, @MarcMogdanz , I've already [fix this bug](https://github.com/actionsflow/actionsflow-action/commit/b02b5308b0adf10d0a1614e5086133f203128ccf).

You do not need to update manually, I have updated the tag [`v1`](https://github.com/actionsflow/actionsflow-action/releases/tag/v1)
 
Just rerun the `Reset Actionsflow Cache` workflow, it'll work fine. 

Let me know if there are any problem. Thanks!

**Comment by MarcMogdanz** [comment]
Yes, it works now. Thanks for the fast fix! :)
