### ISSUE TITLE
Change the Port

### ISSUE THREAD

**Issue by Industrial** [actionsflow/actionsflow#30]
**Context**
I have other programs running on port 3000.

**Alternatives**
Run everything inside a docker container, so that the port can easily be mapped.

**Has the feature been requested before?**
No.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by theowenyoung** [comment]
Hi, @Industrial , If the problem is port conflicting, then you can simplely use another port by using `--port` args?

See the docs: https://actionsflow.github.io/docs/reference/cli/#start

Because the `actionsflow` commands using `node` env, so the part of `actionsflow` just runs in the host.
