### ISSUE TITLE
Webhook Worker May Log GH Personal Access Key

### ISSUE THREAD

**Issue by thadk** [actionsflow/actionsflow#32]
## Description

If I'm not mistaken Personal Access Keys to Github Actions may be logged to Sentry and/or Cloudflare (if it is being tailed somewhere).

### Steps to reproduce

Setup a Slack or other Webhooks integration to https://webhook.actionsflow.workers.dev (https://github.com/actionsflow/webhook2github)

### Expected result

Personal Access Key is kept private or at baseline an explanation in the documentation that this will be logged and an alternative path.

### Actual result

Reading the source code, it seems likely the potentially sensitive GitHub key will be logged into Actionsflow's Sentry.

Maybe setup of the Cloudflare worker could be part of the self-hosted Actionsflow documentation and then this could be mentioned?

**Comment by theowenyoung** [comment]
Thanks for reporting the secure issue, @thadk , I reviewed the related code, and yes, it seemed that if an error occurred, the sensitive information will be send to sentry.

 I'm sorry for this, I made this worker code from another boilerplate,  I also checked the sentry dashboard,  fortunately, there is nothing reported yet!

![image](https://user-images.githubusercontent.com/62473795/150776026-340f3006-5cc7-48da-ad28-8403971e567a.png)

Cause the code has been running for over one year, now I'll totally remove the log, and sentry error report.

The code has been deployed to Worker, https://github.com/actionsflow/webhook2github/commit/2147c987d695c938ff2f17cefce09737b44ba35e

You can also run your own self-hosted webhook bridge version.

Thanks again for the report!

**Comment by thadk** [comment]
Thanks much for the fast response and the underlying functionality which I hadn't seen elsewhere! Had been looking for it for some time. I'll try to write up my experience setting the cloud flare worker up in a PR in case anyone else feels like they want to.

**Comment by theowenyoung** [comment]
Thanks for your interest in Actionsflow! I've actually started a new workflow project in the last few years: Denoflow: <https://github.com/denoflow/denoflow> , which runs in Deno and is also configured with yaml, but is simpler to use and more self-hosted, so if you're interested too, feel free to give it a try! Here's an online [playground](https://playground.owenyoung.com/)

Again, any suggestions would be very helpful to me!
