### ISSUE TITLE
Webhook triggered on every scheduled run on a self-hosted instance

### ISSUE THREAD

**Issue by k0mmsussert0d** [actionsflow/actionsflow#34]
## Description

First things first, I just wanted to say this is an amazing project. The amount of work put into it is immeasurable and so is its potential. Personally, I noticed it as a potential foundation of a self-hosted alternative to Github Actions.

While working on it, I have stumbled upon a type of behavior I don't understand. Initially, I wanted to file a feature request to tailor actionsflow to my needs. However, as I had continued my research, I was becoming more and more convinced that it might actually be a bug that I'm dealing with.

Here's what I've achieved so far.

## Steps to reproduce

Firstly, I created the repository from the actionsflow template and defined a simple *hello world* workflow triggered by a webhook:

<details>
<summary>workflows/test-repo.yml</summary>

```yml
on:
  webhook:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        env:
          method: ${{on.webhook.outputs.method}}
          body: ${{toJson(on.webhook.outputs.body)}}
          headers: ${{toJson(on.webhook.outputs.headers)}}
        run: |
          echo method: $method
          echo headers $headers
          echo body: $body
```
</details>

Then I ran actionsflow in a docker container with the repository mounted as `/data` volume.

After that I created an empty git repository on my local machine and set up a remote for it on the server. Leveraging built-in git hooks functionality, I created a mechanism calling `test-repo` webhook each time the remote is updated.

Here's the script I came up with, utilizing `curl` to call the webhook endpoint. Input data is accepted in accordance to [relevant git docs page](https://git-scm.com/docs/git-receive-pack#_post_receive_hook).

<details>
<summary><repo>/hooks/post-receive</summary>

```bash
#!/bin/bash

WEBHOOK_URL="https://example.com/webhook/test-repo/webhook/"
read oldref newref refname

curl -v \
        -X POST \
        -H "Content-Type: application/json" \
        -d "{\"oldref\": \"${oldref}\", \"newref\": \"${newref}\", \"refname\": \"${refname}\"}" \
        $WEBHOOK_URL
```
</details>

## Expected result

As the result, whenever I push new commit to the remote, the `post-receive` hook is triggered, which in turn triggers the webhook.

<details>
<summary>Here are the logs from the *actionsflow* container:</summary>

```
[18:41:26] INFO actionsflow: Clean the dest folder dist/.cron/1644864086329
[18:41:26] INFO actionsflow: There are 1 immediate tasks, 0 delay tasks
[18:41:26] INFO actionsflow: Run 1 immediate tasks finished, wait for 0 delay tasks to finish...
[18:41:26] INFO actionsflow: All tasks finished, wait for building...
[18:41:26] INFO actionsflow: 1 updates found at trigger [webhook] of workflow [test-repo.yml], workflow file 0-test-repo-webhook.yml build success
[18:41:26] INFO actionsflow: Done.
[18:41:35] INFO actionsflow: Clean the dest folder dist/.cron/1644864095453
[18:41:35] INFO actionsflow: There are 1 immediate tasks, 0 delay tasks
[18:41:35] INFO actionsflow: Run 1 immediate tasks finished, wait for 0 delay tasks to finish...
[18:41:35] INFO actionsflow: All tasks finished, wait for building...
[18:41:35] INFO actionsflow: 1 updates found at trigger [webhook] of workflow [test-repo.yml], workflow file 0-test-repo-webhook.yml build success
[18:41:35] INFO actionsflow: Done.
[0-test-repo-webhook.yml/Print 0] 🚀  Start image=actionsflow/act-environment:v1
[0-test-repo-webhook.yml/Print 0]   🐳  docker run image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-test-repo-webhook.yml/Print 0]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[0-test-repo-webhook.yml/Print 0] ⭐  Run Print outputs
[0-test-repo-webhook.yml/Print 0]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /data/workflow/0] user=
| method: post
| headers { "accept": "*/*", "content-length": "60", "content-type": "application/json", "host": "example.com", "user-agent": "curl/7.64.0", "x-forwarded-for": "172.19.0.1", "x-forwarded-host": "example.com", "x-forwarded-proto": "https", "x-forwarded-ssl": "on", "x-real-ip": "172.19.0.1" }
| body: { "newref": "b", "oldref": "a", "refname": "refs/heads/main" }
[0-test-repo-webhook.yml/Print 0]   ✅  Success - Print outputs
```
</details>

## Actual result

Up to this point, everything operates well and servers the established purpose perfectly. However, for a reason unbeknownst to me, the webhook event is thrown into some eternal queue it never leaves. **Every 5 minutes** *aciontsflow* finds a new update at trigger `webhook` of workflow `test-repo.yml` and decides to run the workflow.

<details>
<summary>Some more logs</summary>

```
[20:30:00] INFO actionsflow: Clean the dest folder dist/.cron/1644870600046
[20:30:00] INFO actionsflow: There are 1 immediate tasks, 0 delay tasks
[20:30:00] INFO actionsflow: Run 1 immediate tasks finished, wait for 0 delay tasks to finish...
[20:30:00] INFO actionsflow: All tasks finished, wait for building...
[20:30:00] INFO actionsflow: 1 updates found at trigger [webhook] of workflow [test-repo.yml], workflow file 0-test-repo-webhook.yml build success
[20:30:00] INFO actionsflow: Done.
[0-test-repo-webhook.yml/Print 0] 🚀  Start image=actionsflow/act-environment:v1
[0-test-repo-webhook.yml/Print 0]   🐳  docker run image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-test-repo-webhook.yml/Print 0]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[0-test-repo-webhook.yml/Print 0] ⭐  Run Print outputs
[0-test-repo-webhook.yml/Print 0]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /data/workflow/0] user=
| method: post
| headers { "accept": "*/*", "content-length": "60", "content-type": "application/json", "host": "example.com",  "user-agent": "curl/7.64.0", "x-forwarded-for": "172.19.0.1", "x-forwarded-host": "example.com", "x-forwarded-proto": "https", "x-forwarded-ssl": "on", "x-real-ip": "172.19.0.1" }
| body: { "newref": "b", "oldref": "a", "refname": "refs/heads/main" }
[0-test-repo-webhook.yml/Print 0]   ✅  Success - Print outputs
```
</details>

I suspect the initiator of these calls to be a `scheduled` run. Correct me if I'm wrong, but documentation doesn't really explain what's the backbone of scheduled runs on a self-hosted instance. Had I used *actionsflow* with Github Actions, I'd go straight to `.github/workflows/actionsflow.yml` and adjust the cron. **Can I do a similar thing on a self-hosted instance?**

That being a case, **why does webhook trigger detects and update on every scheduled run?** I expected it to kick-off the workflow once, when it's called and remain silent until next qualified call arrives.

In attempt to alter this behavior, I tried adding `on.webhook.config.skipSchedule=true`, but that didn't change anything. Workflow would still get started every 5 minutes and **I think it accounts for major inconsistency between documentation and actual behavior that might be potentially recognized as a bug**, as the documentation states that *(...)trigger should skip schedule event.(...) Use this param when you want a trigger to run only manually* when this flag is used.

As the last thing, I'd like to take a note of my relatively low level of experience with *actionsflow*. There might have been a misunderstanding of some of its concepts. If you don't perceive the behavior I've explained as a bug, I'd be very glad to hear your opinions on my way and intends of using *actionsflow*.

**Comment by theowenyoung** [comment]
Hi, @k0mmsussert0d , Thank you for your detailed and understandable report on this issue, it really makes my day to see such a description of the problem! (That's not to say I'm happy to see any bugs, haha)

I initially reproduced the bug locally and I found that the bug was due to an environment variable set by actionsflow when handling the webhook, 

https://github.com/actionsflow/actionsflow/blob/b04b596aae591512f0ccbfd827a3fe677bb2835b/packages/actionsflow/src/server.ts#L32-L38

but it was not restored correctly afterwards, so it caused actionsflow to think that there was a new webhook request every time a cron task was made.

This is a bug, I will fix this soon! Cause most actionsflow users use actionsflow at Github, this problem was not discovered earlier.

Thanks again for the report!

I noticed that you are using self-hosted version, maybe you can give a try my new workflow project Denoflow: https://github.com/denoflow/denoflow , which runs in Deno and is also configured with yaml, designed for self-hosted. It's still at a very early stage, Here's an online [playground](https://playground.owenyoung.com/) , any suggestions would be very helpful to me!

**Comment by theowenyoung** [comment]
Fixed at [actionsflow@1.12.1](https://github.com/actionsflow/actionsflow/releases/tag/actionsflow%401.12.1)

Have a try!

**Comment by k0mmsussert0d** [comment]
Thank you for incredibly fast response time! I've just recreated the container with the newest image and the bug seems to be gone :)

Regarding your other project denoflow, it certainly drew my attention, yet I decided to stick to actionsflow for now as I'm not familiar with deno at all, in contrary to some basic experience with Github Actions. Apart from that, my quick review of deno functionalities and its modules made me wondering if it's even applicable for building some of the solutions I'm interested in, like CI/CD pipelines and generating static websites. The impression I've got from deno is that it's the tool suited for building automated tasks operating on HTTP APIs, but I couldn't see any mentions on how it can be utilized for operating on host filesystem.

**Comment by theowenyoung** [comment]
Sorry I assumed that you are familiar with javascript, if you are not familiar with javascript, then actionsflow is more suitable for you!

In fact, Deno can do anything, including ci and static website generation. I used Denoflow and Deno to generate several feed  websites that I commonly use, such as:  <https://showhn.buzzing.cc/>, <https://hackernews.buzzing.cc/> , denoflow is used to process data fetching , deduplication, save to file system, and then use deno to generate html web pages.

As someone familiar with javascript, I prefer the simplicity and power of Denoflow! Anyway, thanks for your feedback!
