### ISSUE TITLE
Can't separate key from value

### ISSUE THREAD

**Issue by zhgqthomas** [actionsflow/actionsflow#36]
## Description
The Actions always failed if I use Github secrets in my workflow.

### Steps to reproduce
<img width="630" alt="image" src="https://user-images.githubusercontent.com/1124507/158591361-f9e2f4dd-87bb-4441-98a9-a62f88167fd3.png">

### Expected result

Actions run success
### Actual result

Actions run failed.
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/1124507/158591507-0c3d8bac-ac89-47ff-b0ef-aad5b3c59f56.png">

**Comment by theowenyoung** [comment]
Hi, can you provide the exact workflow file content instead of a screenshot? or a link to your repo is also fine!

**Comment by theowenyoung** [comment]
Solved, there is a `\n` character at secret value.
