### ISSUE TITLE
reference more awesome github actions list

### ISSUE THREAD

**Issue by gasolin** [actionsflow/actionsflow#37]
**Context**

> What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?

In doc there are plenty actionsflow official triggers and actions, but it does not reveal the full strength of the actionsflow (can reuse any github action in steps)

suggest to list some of notification actions like https://github.com/sdras/awesome-actions#notifications-and-messages in actionsflow's doc

to out reach more users, might also worth to list actionsflow's official triggers/actions to

https://github.com/sdras/awesome-actions

**Alternatives**

> Can you achieve the same result doing it in an alternative way? Is the alternative considerable?

search and self learn the github actions

**Has the feature been requested before?**

NA

**If the feature request is approved, would you be willing to submit a PR?**

No

**Comment by theowenyoung** [comment]
Thanks your kind advice!

I've add this repo at actions doc:  <https://github.com/actionsflow/actionsflow/blob/main/docs/actions.md>
