### ISSUE TITLE
Use GitHub secrets in trigger config

### ISSUE THREAD

**Issue by MarcMogdanz** [actionsflow/actionsflow#6]
**Context**

I'd like to not just use GitHub Secrets in my action steps but rather also in the config setup of my trigger. Currently doing so always throws an error

```yml
on:
  rss:
    url:
      - "${{ RSS_FEED }}"
```

Trying this [fails](https://github.com/MarcMogdanz/actionsflow-workflows/runs/1211523898?check_suite_focus=true). I don't know how to prevent leaking the secret as e.g. when an URL is not available (because the web server is down or whatever) it sometimes prints the url to the console 

**Alternatives**

I don't know of any way

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

Maybe if I have enough inputs on what to do and where

**Comment by theowenyoung** [comment]
@MarcMogdanz The right way to use secrets in the trigger is look like this:

```yaml
on:
  rss:
    url:
      - "${{ secrets.RSS_FEED }}"
```

You missed the `secrets`.

Here is the doc: https://actionsflow.github.io/docs/workflow/#on

> I don't know how to prevent leaking the secret as e.g. when an URL is not available (because the web server is down or whatever) it sometimes prints the url to the console

You should use `"${{ secrets.RSS_FEED }}"`, then Github will mark your secret.

**Comment by theowenyoung** [comment]
I'll close this issue now, feel free to tell me if you have further question.
